### ISSUE TITLE
Error in logout from identityServer4 vm.PostLogoutRedirectUri= null and , logout= null

### ISSUE THREAD

**Issue by aboelkassem** [LiveOrDevTrying/IdentityServer4-Angular-.NET-Core-WebAPI-Boilerplate#9]
when trying to logout from identity "http://localhost:5000/Account/Logout" by confirming yes but it throws that exception and although accessToken and sessionEdnId store in local cookies but it says that I'm not authorized

```
An unhandled exception occurred while processing the request.
ArgumentException: Value cannot be null or empty. (Parameter 'url')


Microsoft.AspNetCore.Mvc.ControllerBase.Redirect(string url)
IdentityServer4.Quickstart.UI.AccountController.Logout(LogoutInputModel model) in AccountController.cs

                return Redirect(vm.PostLogoutRedirectUri);

```

**Comment by LiveOrDevTrying** [comment]
Hi aboelkassem,

Thank you for your message. Are you using Implicit flow? If yes, you need to specify a redirect url that identityserver4 will redirect you to following a successful logout.  

To achieve this, the redirect url needs to be specified in the Client you created in Config.cs in IdentityServer4. Additionally, in the Angular CLI webapp, we are using OAuthServer from angular-oauth2-oidc. In the app.component.ts, we also have to specify the post logout redirect uri with the following line of code:

this.oauthService.postLogoutRedirectUri = this.globalsService.landingPageUri;

Where in your case, this.globalsService.landingPageUri would be the url to redirect the user to post logout. I put this line in ngOnInit so it is only executed once when the app is ran.

Please let me know if that helps, if there are any questions, and / or if we were able to get your error resolved. Thanks again!
Rob

**Comment by aboelkassem** [comment]
yeah, I figure that out and forget to close this issue.

I was testing from identityServerUrl `http://localhost:5000`, not from angular client that causes the returning `LogoutId=null` so I follow what exactly you said to put `this.oauthService.postLogoutRedirectUri = this.globalsService.landingPageUri;` on `ngOnInit` life cycle and it's everything works fine about logging out.

thanks for your help

**Comment by LiveOrDevTrying** [comment]
This is great news! Thanks again for using this repo, and I will be posting an updated version of the boilerplate over this weekend.

Cheers,
Rob
